spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rennala
    username: root
    password: Password1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

  application:
    name: USER-SERVICE
server:
  port: 4000

management:
  security:
    enabled: false